# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
name-template: 'v$NEXT_PATCH_VERSION 🌈'
tag-template: 'v$NEXT_PATCH_VERSION'
version-template: $MAJOR.$MINOR.$PATCH
autolabeler:
  - label: 'chore'
    files:
      - '*.md'
  - label: 'bug'
    branch:
      - '/fix.+/'
  - label: 'feature'
    branch:
      - '/feat.+/'
  - label: 'enhancement'
    branch:
      - '/perf.+/'
  - label: 'cicd'
    branch:
      - '/cicd.+/'
# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'cicd'
      - 'chore'
      - 'dependencies'
exclude-labels:
  - reverted
  - no-changelog
  - skip-changelog
  - invalid
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
template: |
  ## What’s Changed
  $CHANGES
